sun4i: update pack script and some fix

diff --git a/tools/pack/pack b/tools/pack/pack
--- a/tools/pack/pack
+++ b/tools/pack/pack
@@ -11,27 +11,58 @@ TOOLS_DIR=${ROOT_DIR}/pctools/linux
 export PATH=${TOOLS_DIR}/mod_update:${TOOLS_DIR}/eDragonEx:${TOOLS_DIR}/fsbuild200:$PATH
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${TOOLS_DIR}/libs
 
+BOARD_TYPE=evb1.1
+BOOT_TYPE=nand
+PRODUCT_TYPE=linux
 
-if [ $# = 0 ]; then
-MEDIA=nand
-echo "default packing for nand"
+show_help()
+{
+printf "
+NAME
+    pack - The pack tools for linux firmware
+
+SYNOPSIS
+    pack [-h] [-b boot_type] [-B board_type] [-p product_type]
+
+OPTIONS
+    -h                  Display help message
+    -b [boot_type]      Boot media type, e.g. nand, sdcard, nor,...
+    -B [board_type]     Board type, e.g. evb1.1, evb1.2A, evb1.2B,...
+    -p [product_type]   Product type, e.g. linux, crane,...\n\n
+"
+
+}
+
+while getopts hb:B:p: OPTION
+do
+	case $OPTION in
+	h) show_help
+	exit 0
+	;;
+	p) PRODUCT_TYPE=$OPTARG
+	;;
+	b) BOOT_TYPE=$OPTARG
+	;;
+	B) BOARD_TYPE=$OPTARG
+	;;
+	*) show_help
+	exit 0
+	;;
+esac
+done
+
+####################################
+# Do some check
+####################################
+if [ ! -f "eFex/sys_config_${PRODUCT_TYPE}.fex" -o \
+   ! -f eFex/sys_config1_${BOARD_TYPE}.fex -o \
+   ! -f wboot/image_${PRODUCT_TYPE}.cfg -o \
+   ! -d eGon/storage_media/$BOOT_TYPE ]; then
+   printf "\nError: Missing some files\n"
+   show_help
+   exit 1
 fi
 
-if [ $# = 1 ]; then
-	if [ "$1" = "nand" ]; then
-		MEDIA=nand
-		echo "packing for nand"
-	elif [ "$1" = "sdcard" ]; then
-		MEDIA=sdcard
-		echo "packing for sdcard"
-	else
-		echo "Wrong media type"
-		echo "currently supported media type is nand or sdcard"
-		echo "./pack nand	-- to pack for nand"
-		echo "./pack sdcard	-- to pack for sdcard"
-		exit 1
-	fi
-fi
 
 ####################################
 # Clean before pack
@@ -44,14 +75,20 @@ mkdir out/
 ####################################
 # Copy all needed files to out dir
 ####################################
-cp -rf eFex/sys_config.fex eFex/sys_config1.fex eFex/split_xxxx.fex eFex/card/mbr.fex \
-   eGon/storage_media/$MEDIA/boot0.bin eGon/storage_media/$MEDIA/boot1.bin \
-   wboot/bootfs wboot/image_$MEDIA.cfg wboot/bootfs.ini \
+
+cp eFex/sys_config_${PRODUCT_TYPE}.fex out/sys_config.fex
+cp eFex/sys_config1_${BOARD_TYPE}.fex out/sys_config1.fex
+cp wboot/image_${PRODUCT_TYPE}.cfg out/image.cfg
+
+cp -rf eFex/split_xxxx.fex eFex/card/mbr.fex \
+   eGon/storage_media/$BOOT_TYPE/boot0.bin eGon/storage_media/$BOOT_TYPE/boot1.bin \
+   wboot/bootfs wboot/bootfs.ini \
    out/
-mv out/bootfs/boot_$MEDIA.axf out/bootfs/boot.axf
-mv out/bootfs/sprite_$MEDIA.axf out/bootfs/sprite.axf
-cp -rf eGon/storage_media/$MEDIA/boot0.bin out/card_boot0.fex
-cp -rf eGon/storage_media/$MEDIA/boot1.bin out/card_boot1.fex
+
+mv out/bootfs/boot_$BOOT_TYPE.axf out/bootfs/boot.axf
+mv out/bootfs/sprite_$BOOT_TYPE.axf out/bootfs/sprite.axf
+cp -rf eGon/storage_media/$BOOT_TYPE/boot0.bin out/card_boot0.fex
+cp -rf eGon/storage_media/$BOOT_TYPE/boot1.bin out/card_boot1.fex
 
 ####################################
 # Enter work dir and begin to pack
@@ -62,9 +99,15 @@ cd out/
 # Convert path to linux style
 ####################################
 sed -i 's/\\bootfs/\/bootfs/g' bootfs.ini
-sed -i 's/\\\\/\//g' image_$MEDIA.cfg
+sed -i 's/\\\\/\//g' image.cfg
+sed -i 's/imagename/;imagename/g' image.cfg
+
+IMG_NAME="${PRODUCT_TYPE}-${BOARD_TYPE}-${BOOT_TYPE}.img"
+echo "imagename = $IMG_NAME" >> image.cfg
+echo "" >> image.cfg
 
 ln -s ../wboot/*.fex .
+dos2unix sys_config.fex
 script_old sys_config.fex
 script sys_config1.fex
 update_23 sys_config1.bin boot0.bin boot1.bin
@@ -74,9 +117,9 @@ cp sys_config1.bin bootfs/script.bin
 
 update_mbr sys_config.bin mbr.fex
 fsbuild bootfs.ini split_xxxx.fex
-dragon image_$MEDIA.cfg
+dragon image.cfg
 cd -
 
 printf "\nPack Done!\n\n"
 echo "==========================image is at==========================="
-echo "$ROOT_DIR/out/ePDKv100_$MEDIA.img"
+echo "$ROOT_DIR/out/$IMG_NAME"
